spring:
  datasource:
    url: jdbc:h2:~/jpa-basic
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    database: H2
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true